# Generated by Django 3.2.9 on 2021-12-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0007_alter_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
